name: Cache job set

on:
  schedule:
    - cron: "25 16 * * 2"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install npm packages
        run: npm install
      - name: Cache job set
        run: ./src/jobs/bin/cacheJobSet.ts
      - name: Commit cache changes, if any
        run: bash ./bin/commit-cache-changes
