name: Check all member data

on:
  schedule:
    - cron: "25 16 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install npm packages
        run: npm install
      - name: Check all member data
        run: ./src/memberData/bin/checkMembers.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
