name: Build website (incl fetching and checking data)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Run npm install
        run: npm install
      - name: Cache job set
        run: ./src/jobs/bin/cacheJobSet.ts
      - name: Commit cache changes, if any
        run: bash ./bin/commit-cache-changes
      - name: Check all member data
        run: ./src/members/bin/checkMembers.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Make OpenGraph image
        run: ./src/members/bin/makeOpenGraphImage.ts
      - name: Build website files
        uses: withastro/action@b7d53628f8b666036b0238aadb0b984a2a489f26
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
